openapi: 3.0.0
info:
  title: Slack API
  description: Slack Web API
  version: 1.0.0
servers:
  - url: https://slack.com/api
paths:
  /chat.postMessage:
    post:
      operationId: chat_postMessage
      summary: Sends a message to a channel.
      security:
        - slack_auth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                channel:
                  type: string
                  description: Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name.
                text:
                  type: string
                  description: Text of the message to send.
              required:
                - channel
                - text
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  channel:
                    type: string
                  ts:
                    type: string
                  message:
                    type: object
components:
  securitySchemes:
    slack_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/v2/authorize
          tokenUrl: https://slack.com/api/oauth.v2.access
          scopes:
            chat:write: Used to repond to user and post messages to channels
           
